// <auto-generated />
using System;
using BuckeyeMarketplaceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuckeyeMarketplaceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401200208_AddStockQuantityToProduct")]
    partial class AddStockQuantityToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BuckeyeMarketplaceAPI.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("BuckeyeMarketplaceAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SellerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BuckeyeMarketplaceAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Textbooks",
                            Description = "Comprehensive textbook for IS fundamentals",
                            ImageUrl = "https://m.media-amazon.com/images/I/61wDhC8nNGL._AC_UF1000,1000_QL80_.jpg",
                            PostedDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 89.99m,
                            SellerName = "John Smith",
                            StockQuantity = 10,
                            Title = "Introduction to Information Systems textbook"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Apparel",
                            Description = "Official Ohio State University sweatshirt",
                            ImageUrl = "",
                            PostedDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 34.99m,
                            SellerName = "Emma Johnson",
                            StockQuantity = 10,
                            Title = "Ohio State Sweatshirt - Medium"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Textbooks",
                            Description = "Advanced organic chemistry reference",
                            ImageUrl = "",
                            PostedDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 129.99m,
                            SellerName = "Alex Martinez",
                            StockQuantity = 10,
                            Title = "Organic Chemistry Textbook"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Electronics",
                            Description = "LED desk lamp with adjustable brightness",
                            ImageUrl = "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRQDvUa6IAUeyY01b9MIIP3a8rZcNZQq-kVNR0ylUQpERW9KsT7UtDHQD5Hab91d8Q-JZGCopcfrnPiXptjLaRR2qXx1KHXM5RnAbyR-nYfEB7r_4Hyhxt0rA",
                            PostedDate = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 24.99m,
                            SellerName = "Sarah Lee",
                            StockQuantity = 10,
                            Title = "Desk Lamp"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Apparel",
                            Description = "Warm winter coat with waterproof exterior",
                            ImageUrl = "",
                            PostedDate = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 99.99m,
                            SellerName = "Michael Brown",
                            StockQuantity = 10,
                            Title = "Winter Coat"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            Description = "55-inch 4K Smart TV",
                            ImageUrl = "",
                            PostedDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 399.99m,
                            SellerName = "David Wilson",
                            StockQuantity = 10,
                            Title = "TV"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Appliances",
                            Description = "Compact mini fridge for dorm or office",
                            ImageUrl = "",
                            PostedDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 79.99m,
                            SellerName = "Jessica Garcia",
                            StockQuantity = 10,
                            Title = "Mini Refrigerator"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Apparel",
                            Description = "Official Ohio State University jacket",
                            ImageUrl = "",
                            PostedDate = new DateTime(2026, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 64.99m,
                            SellerName = "Christopher Davis",
                            StockQuantity = 10,
                            Title = "Ohio State Jacket"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Home Decor",
                            Description = "Large wall mirror with wooden frame",
                            ImageUrl = "",
                            PostedDate = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 44.99m,
                            SellerName = "Amanda Rodriguez",
                            StockQuantity = 10,
                            Title = "Mirror"
                        });
                });

            modelBuilder.Entity("BuckeyeMarketplaceAPI.Models.CartItem", b =>
                {
                    b.HasOne("BuckeyeMarketplaceAPI.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BuckeyeMarketplaceAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BuckeyeMarketplaceAPI.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
